const teTexts = {
    // texts to display about teas
    tea: 'Understanding the “Art of Tea” in its entirety is an age old question that we are still continuously exploring today. With brand new tea knowledge and discoveries unveiling themselves each day, the journey into the world of tea is an exciting and limitless adventure with room for us all to explore, connect and interact.Being an engaged crew of tea educators, we have been fortunate enough to receive many wonderful insights on tea from its history to its preparation, all the while diving deeper into the various varietals that stem from the miraculously versatile camellia sinensis plant. While we can’t begin to know everything about tea, we hope that we can help guide you with our extensive knowledge of what we do know about tea in this section.',
    teaWhite: 'White tea is comprised of new, young tea leaves and buds from the camellia sinensis plant and is only harvested for a few weeks each spring in the northern district of Fujian, China. The leaves are generally picked in mid-March to early April and only on days when it is not rainy or humid. Just like champagne, white tea can only be called “white tea” if it comes from the Fujian province. White tea gets its name from a silvery type down that covers the leaves and unopened buds, known as “Hao.”or many years it was believed that white tea was discovered during the Song Dynasty (920-1269), however, even earlier references to white tea have been traced as far back as the Tang Dynasty (618-907). At that time in history, white tea preparation was a very different experience than it is today: early harvest white tea leaves appeared solely in compressed cakes and broken pieces were steeped in earthenware kettles.',
    teaGreen: 'Green tea, also known as unoxidized tea, is made solely from the leaves of the camellia sinensis plant. The leaves are plucked, slightly withered, then immediately cooked to preserve the green quality and prevent oxidization. As a result of these methods, green teas have a much higher concentration of chlorophyll, polyphenols and antioxidants than other tea types. The growing conditions for green tea can be broken down between two different types: sun grown and shade grown. The leaves are generally harvested three times a year with the first flush producing the highest quality leaves. The heating process differs greatly depending on the region and the tea maker’s techniques. Some of the mainstream methods of manufacturing green tea include: Pan Firing - Chinese green teas are often pan or wok roasted to neutralize the natural enzymes then dried, which generally results in a pale green color such as our Dragonwell.',
    teaPuerh: 'Pu-erh tea, known as “black tea” in the Far East part of the world, originates from the Yunnan province of China and is named after the market town in which it was first developed. Pu-erh tea is post-fermented, which means that the tea leaves go through a microbial fermentation process after they have been dried and rolled, causing the leaves to darken and change in flavor. This process allows the teas to not only improve with age like a fine wine, but many pu-erhs are able to retain their freshness for up to fifty years! Pu-erh teas can be found in compressed brick form or in loose leaf form and can be made from both green and black tea leaves.',
    teaOolong: 'Oolong (Wu-lung) tea originates from China and is actually transliterated from two words meaning “black” and “dragon” in English. Besides its inherent meaning, the two words describe the shape of the oolong leaves in their novel state. Oolong tea goes through a unique semi-oxidization process that ranges from 1% - 99%. Shortly after picking, the leaves are withered and semi-oxidized in the sun then shade dried. After this they are basket-tossed to break down the cells on the surface of the leaves and wok fired, which halts the oxidization process. Heating methods include masterfully hand roasting the tea leaves in multiple steps which generally take place throughout the night. Oolongs are often processed over charcoal or wood which gives a unique flavor to the various finishing styles. Finally, the leaves are curled or rolled into crispy shapes that resemble tiny black dragons, hence the descriptive name....',
    teaBlack: 'Black tea, also known as “red tea” in China for its rich, reddish infusion, is unique in that it is comprised from two different forms of the camellia sinensis plant: camellia sinensis sinensis and camellia sinensis assamica. Camellia Sinensis Sinensis yields shorter leaves and is primarily used in China and other neighboring East Asian countries. Camellia Sinensis Assamica has larger leaves and is used in parts of India and Sri Lanka. Dry black tea leaves are 100% oxidized, leaving them with a blackened color, thus earning its namesake. While the method in which it is produced varies from region to region, the process always involves withering, rolling, oxidization and drying. There are two primary methods of processing the leaves before they are graded:',
}

export { teTexts }
